import os
import glob
from pathlib import PurePath

DATA_DIR = PurePath(os.environ['DATA'], 'STEREO/L7tum/')

# Directory hosting the prepped STEREO FITS files
PREPPED_DATA_DIR = PurePath(DATA_DIR, 'prep_fits')
# Path of the of csv file containing the coordinates and labels of the training set
TRAINING_SET_CSV = PurePath(DATA_DIR, 'training_set/targets.csv')
# Output directories for data and figures generated by mballtrack: tracked positions, overlays, etc...
OUTPUT_DIR = PurePath(os.environ['DATA'], 'STEREO/L7tum/mballtrack_output')
FIG_DIR = PurePath(OUTPUT_DIR, 'figures')
# Physical constants for unit conversion
DSUN_OBS = 1.433675e6  # Solar diameter in km
RSUN = DSUN_OBS/2  # Solar radius in km
DT = 5*60 # 5 minutes time interval between each frame
CDELT2 = 0.0141875720451562 # solar radius / px
VUNIT = CDELT2 * RSUN/DT


# Default input dictionnary for magnetic balltracking, fixed parameters not subject to parameter sweeps
mbt_dict = {
    "nt": 10,
    "polarity": 1,
    "track_emergence": False,
    "datafiles": sorted(glob.glob(str(PurePath(PREPPED_DATA_DIR, '*.fits')))),
    "do_plots": False,
    "astropy": True,
    "verbose": False,
    "fig_dir": FIG_DIR
}

ball_params = {
    "rs": 4,
    "am": 1,
    "dp": 0.3,
    "tdx": 1,
    "tdy": 30,
    "zdamping": 1,
    "ballspacing": 15,
    "intsteps": 20,
    "mag_thresh": 3.5,
    "noise_level": 2
}

